plugins {
    id 'com.android.application'
}

android {
    namespace 'ir.dangidongi.app'
    compileSdk 34

    defaultConfig {
        applicationId "ir.dangidongi.app"
        minSdk 24
        targetSdk 34
        versionCode 1
        versionName "1.0"
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}

// بدون هیچ کتابخانه‌ی خارجی — فقط API خود اندروید
dependencies {
}
